apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-private
  region: us-east-1

availabilityZones:
  - us-east-1a
  - us-east-1b

iam:
  withOIDC: true

privateCluster:
  enabled: true

managedNodeGroups:
  - name: mng1
    instanceType: m5.large
    desiredCapacity: 2
    privateNetworking: true
